name: Deploy to EC2 via SSM

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 📦 Checkout
      uses: actions/checkout@v4

    - name: 🔑 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 🚀 Execute deployment on EC2 via SSM
      run: |
        set -e
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
          --parameters 'commands=["git config --global --add safe.directory /home/ubuntu/project7 && cd /home/ubuntu/project7/server && git pull origin main && sudo make prod-ec2"]' \
          --region ${{ env.AWS_REGION }} \
          --timeout-seconds 300
        echo "SSM command executed successfully"
