name: Django Run Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  django-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./server/django

      - name: Run Tests
        run: |
          python3 manage.py test
        working-directory: ./server/django
