name: Lint and Format Check

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Pythonバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
      

    - name: Run flake8
      run: |
        flake8 .
      working-directory: ./server/django

    - name: Run black
      run: |
        black --check .
      working-directory: ./server/django

    - name: Run isort
      run: |
        isort --check-only .
      working-directory: ./server/django
