name: Python Code Check

on:
  pull_request:
    branches:
      - dev

jobs:
  python_code_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Pythonバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.6.9
      

    - name: Run ruff check .
      run: |
        ruff check .
      working-directory: ./server/django

    - name: Run ruff format --check
      run: |
        ruff format --check .
      working-directory: ./server/django

